rework iSCSI network configuration

diff --git a/playbooks/roles/ucluster/templates/cloud-config.j2 b/playbooks/roles/ucluster/templates/cloud-config.j2
--- a/playbooks/roles/ucluster/templates/cloud-config.j2
+++ b/playbooks/roles/ucluster/templates/cloud-config.j2
@@ -10,8 +10,9 @@ users:
 apt:
   http_proxy: {{ proxy.http }}
   https_proxy: {{ proxy.https }}
+{% endif %}
 write_files:
-- path: /root/confignet.sh
+- path: /root/config-mgmtnet.sh
   content: |
     #!/bin/bash
     mask2cidr() {
@@ -36,14 +37,9 @@ write_files:
     vmtoolsd --cmd 'info-get guestinfo.ovfEnv' > /tmp/ovfenv
     IPAddress=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.ip.0.address" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
     SubnetMask=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.ip.0.netmask" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
+    prefix=$(mask2cidr $SubnetMask)
     Gateway=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.route.0.gateway" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
     DNS=$(sed -n 's/.*Property oe:key="guestinfo.dns.servers" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
-
-    IPAddress2=$(sed -n 's/.*Property oe:key="guestinfo.interface.1.ip.0.address" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
-    SubnetMask2=$(sed -n 's/.*Property oe:key="guestinfo.interface.1.ip.0.netmask" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
-    prefix1=$(mask2cidr $SubnetMask)
-    prefix2=$(mask2cidr $SubnetMask2)
- 
     cat > /etc/netplan/50-cloud-init.yaml <<EOF
     network:
       version: 2
@@ -51,16 +47,53 @@ write_files:
       ethernets:
         {{ rancher_iface }}:
           addresses: 
-            - $IPAddress/$prefix1
+            - $IPAddress/$prefix
           gateway4: $Gateway
           nameservers:
             addresses : [$DNS]
-        {{ iscsi2_iface }}:
-          mtu: 9000
-          addresses: 
-            - $IPAddress2/$prefix2
     EOF
     sudo netplan apply
+
+{% if iscsi1_portgroup is defined %}
+- path: /root/config-iscsi1.sh
+  content: |
+    #!/bin/bash
+    mask2cidr() {
+        nbits=0
+        IFS=.
+        for dec in $1 ; do
+            case $dec in
+                255) let nbits+=8;;
+                254) let nbits+=7;;
+                252) let nbits+=6;;
+                248) let nbits+=5;;
+                240) let nbits+=4;;
+                224) let nbits+=3;;
+                192) let nbits+=2;;
+                128) let nbits+=1;;
+                0);;
+                *) echo "Error: $dec is not recognised"; exit 1
+            esac
+        done
+        echo "$nbits"
+    }
+    vmtoolsd --cmd 'info-get guestinfo.ovfEnv' > /tmp/ovfenv
+    IPAddress=$(sed -n 's/.*Property oe:key="guestinfo.interface.1.ip.0.address" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
+    SubnetMask=$(sed -n 's/.*Property oe:key="guestinfo.interface.1.ip.0.netmask" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
+    prefix=$(mask2cidr $SubnetMask)
+    cat > /etc/netplan/iscsi1.yaml <<EOF
+    network:
+      version: 2
+      renderer: networkd
+      ethernets:
+        {{ iscsi1_iface }}:
+          mtu: 9000
+          addresses: 
+            - $IPAddress/$prefix
+    EOF
+    sudo netplan apply
+{% endif %}
+{% if proxy is defined %}
 - path: /etc/environment
   owner: root:root
   content: |
@@ -80,4 +113,4 @@ ca-certs:
 {% endfor %}
 
 runcmd:
-- bash /root/confignet.sh
+- bash /root/config-mgmtnet.sh
